### ISSUE TITLE
Protege plugin broken in P5 b21

### ISSUE THREAD

**Issue by dosumis** [hdietze/obographview#6]
Pressing
![image](https://cloud.githubusercontent.com/assets/112839/12357706/5eb80892-bba1-11e5-9741-5733a75d47cb.png)
 =>

Uncaught Exception in thread 'AWT-EventQueue-0' 
java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLOntologyManager.getOntologyFormat(Lorg/semanticweb/owlapi/model/OWLOntology;)Lorg/semanticweb/owlapi/model/OWLOntologyFormat;
    at owltools.graph.OWLGraphWrapper.<init>(OWLGraphWrapper.java:259) ~[na:na]
    at org.geneontology.view.OboGraphView.update(OboGraphView.java:177) ~[na:na]
    at org.geneontology.view.OboGraphView.access$200(OboGraphView.java:40) ~[na:na]
    at org.geneontology.view.OboGraphView$3$1.run(OboGraphView.java:90) ~[na:na]
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) ~[na:1.8.0_40]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) ~[na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]

Happens with toy ontologies as well as full GO.

**Comment by premkumar-masilamani** [comment]
Hi Team - I get the same error now with any Ontology file. Is there a fix available?.

**Comment by cmungall** [comment]
I would like to port to P5 but unfortunately we don't have anyone allocated to work on this at the moment so I can't give a date when a fix will be available
